INSERT INTO items (owner_id,title,description,price,genre)VALUES
(1,'Brazen and the Beast','This is a brand new romance book by Author Sarah MacLean',12,'Romance' ),
(2,'Brazen and the Beast','This is a used romance book by Author Sarah MacLean',5,'Romance' ),
(3,'Brazen and the Beast','This is a romance book by Author Sarah MacLean',8,'Romance' ),
(4,'Brazen and the Beast','This is a brand new romance book by Author Sarah MacLean',20,'Romance' ),
(5,'Brazen and the Beast','This is a used romance book by Author Sarah MacLean',9,'Romance' ),
(6,'Brazen and the Beast','This is a brand new romance book by Author Sarah MacLean',13,'Romance' ),
(7,'Brazen and the Beast','This is a used romance book by Author Sarah MacLean',10,'Romance' ),
(8,'Brazen and the Beast','This is a used romance book by Author Sarah MacLean',8,'Romance' ),
(9,'Brazen and the Beast','This is a used romance book by Author Sarah MacLean',10,'Romance' ),
(10,'Brazen and the Beast','This is a brand new romance book by Author Sarah MacLean',16,'Romance' ),
(11,'Royal Holiday','This is a brand new book , a romance book by Jasmine Guillory', 20, 'Romance'),
(12,'Royal Holiday','This is a brand new book , a romance book by Jasmine Guillory', 20, 'Romance'),
(13,'Royal Holiday','This is a brand new book , a romance book by Jasmine Guillory', 20, 'Romance'),
(14,'Royal Holiday','This is a brand new book , a romance book by Jasmine Guillory', 20, 'Romance'),
(15,'Royal Holiday','This is a used book , a romance book by Jasmine Guillory', 15, 'Romance'),
(16,'Royal Holiday','This is a used book , a romance book by Jasmine Guillory', 14, 'Romance'),
(17,'Royal Holiday','This is a used book , a romance book by Jasmine Guillory', 13, 'Romance'),
(18,'Royal Holiday','This is a used book , a romance book by Jasmine Guillory', 15, 'Romance'),
(19,'The Savior', 'This is a brand new book , a romance book by J.R Ward', 50, 'Romance'),
(20,'The Savior', 'This is a brand new book , a romance book by J.R Ward', 50, 'Romance'),
(21,'The Savior', 'This is a brand new book , a romance book by J.R Ward', 50, 'Romance'),
(22,'The Savior', 'This is a brand new book , a romance book by J.R Ward', 50, 'Romance'),
(23,'The Savior', 'This is a brand new book , a romance book by J.R Ward', 50, 'Romance'),
(24,'The Night Fire', 'This is used book the famous mystery book by Michael Connelly',20,'Mystery'),
(25,'The Night Fire', 'This is used book the famous mystery book by Michael Connelly',25,'Mystery'),
(26,'The Night Fire', 'This is used book the famous mystery book by Michael Connelly',23,'Mystery'),
(27,'The Night Fire', 'This is used book the famous mystery book by Michael Connelly',22,'Mystery'),
(28,'The Night Fire', 'This is used book the famous mystery book by Michael Connelly',25,'Mystery'),
(1,'The Adventures of Sherlock Holmes', 'This is very rare used book the famous mystery book by Sir Arthur Conan Doyle ',300,'Mystery'),
(2,'The Adventures of Sherlock Holmes', 'This is very rare used book the famous mystery book by Sir Arthur Conan Doyle ',299,'Mystery'),
(3,'The Adventures of Sherlock Holmes', 'This is very rare used book the famous mystery book by Sir Arthur Conan Doyle ',310,'Mystery'),
(4,'And Then There Were None','This is a brand new Mystery book by Agatha Christie',20,'Mystery' ),
(5,'And Then There Were None','This is a brand new Mystery book by Agatha Christie',9,'Mystery' ),
(6,'And Then There Were None','This is a brand new Mystery book by Agatha Christie',13,'Mystery' ),
(7,'And Then There Were None','This is a brand new Mystery book by Agatha Christie',10,'Mystery' ),
(8,'And Then There Were None','This is a brand new Mystery book by Agatha Christie',8,'Mystery' ),
(9,'One Step Too Far','This is a brand new Mystery book by Lisa Gardner',8,'Mystery' ),
(10,'One Step Too Far','This is a brand new Mystery book by Lisa Gardner',8,'Mystery' ),
(11,'One Step Too Far','This is a brand new Mystery book by Lisa Gardner',8,'Mystery' ),
(12,'One Step Too Far','This is a brand new Mystery book by Lisa Gardner',8,'Mystery' ),
(13,'One Step Too Far','This is a brand new Mystery book by Lisa Gardner',8,'Mystery' ),
(14,'Find Me', 'This book is a used book by author Alafair Burke',11, 'Mystery'),
(15,'Find Me', 'This book is a used book by author Alafair Burke',12, 'Mystery'),
(16,'Find Me', 'This book is a used book by author Alafair Burke',13, 'Mystery'),
(17,'Find Me', 'This book is a used book by author Alafair Burke',14, 'Mystery'),
(18,'Find Me', 'This book is a used book by author Alafair Burke',10, 'Mystery'),
(19,'Find Me', 'This book is a used book by author Alafair Burke',12, 'Mystery'),
(20,'Find Me', 'This book is a used book by author Alafair Burke',13, 'Mystery'),
(21,'The Other Family', 'This book is a new book by author Wendy Corsi Staub',13, 'Mystery'),
(22,'The Other Family', 'This book is a used book by author Wendy Corsi Staub',7, 'Mystery'),
(23,'The Other Family', 'This book is a used book by author Wendy Corsi Staub',5, 'Mystery'),
(24,'The Other Family', 'This book is a new book by author Wendy Corsi Staub',13, 'Mystery'),
(25,'A Flicker in the Dark', 'This book is a new book by author Stacy Willingham',13, 'Mystery'),
(26,'A Flicker in the Dark', 'This book is a new book by author Stacy Willingham',13, 'Mystery'),
(27,'A Flicker in the Dark', 'This book is a new book by author Stacy Willingham',13, 'Mystery'),
(28,'A Flicker in the Dark', 'This book is a new book by author Stacy Willingham',13, 'Mystery'),
(1,'The Silent Patient', 'This book is a new book by author Alex Michaelides',13, 'Horror'),
(2,'The Silent Patient', 'This book is a new book by author Alex Michaelides',13, 'Horror'),
(3,'The Silent Patient', 'This book is a new book by author Alex Michaelides',13, 'Horror'),
(4,'The Silent Patient', 'This book is a new book by author Alex Michaelides',13, 'Horror'),
(5,'The Silent Patient', 'This book is a new book by author Alex Michaelides',13, 'Horror'),
(6,'The Paris Apartment', 'This book is used book from Lucey Foley',13, 'Horror'),
(7,'The Paris Apartment', 'This book is used book from Lucey Foley',13, 'Horror'),
(8,'The Paris Apartment', 'This book is used book from Lucey Foley',13, 'Horror'),
(9,'The Paris Apartment', 'This book is used book from Lucey Foley',13, 'Horror'),
(10,'The Paris Apartment', 'This book is used book from Lucey Foley',13, 'Horror'),
(11,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(12,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(13,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(14,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(15,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(16,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(17,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(18,'Birdbox', 'This book is best seller book the famous birdbox by Author Josh Malerman',40, 'Horror'),
(19,'Carrie','The most horror book by the famous Stephen King, this is used book',30,'Horror'),
(20,'Carrie','The most horror book by the famous Stephen King, this is used book',30,'Horror'),
(21,'Carrie','The most horror book by the famous Stephen King, this is used book',35,'Horror'),
(22,'Carrie','The most horror book by the famous Stephen King, this is used book',50,'Horror'),
(23,'The Haunting of Hill House', 'The famous novel adapted by netflix , the author is Shirley Jackson',25,'Horror'),
(24,'The Haunting of Hill House', 'The famous novel adapted by netflix , the author is Shirley Jackson',25,'Horror'),
(25,'The Haunting of Hill House', 'The famous novel adapted by netflix , the author is Shirley Jackson',25,'Horror'),
(26,'The Haunting of Hill House', 'The famous novel adapted by netflix , the author is Shirley Jackson',25,'Horror'),
(27,'The Haunting of Hill House', 'The famous novel adapted by netflix , the author is Shirley Jackson',25,'Horror'),
(28,'The Haunting of Hill House', 'The famous novel adapted by netflix , the author is Shirley Jackson',25,'Horror'),
(1,'The Subtle Art of Not Giving a F*ck', 'Self Development book by Mark Manson',15,'Self Development'),
(2,'The Subtle Art of Not Giving a F*ck', 'Self Development book by Mark Manson',15,'Self Development'),
(3,'The Subtle Art of Not Giving a F*ck', 'Self Development book by Mark Manson',15,'Self Development'),
(4,'The Subtle Art of Not Giving a F*ck', 'Self Development book by Mark Manson',15,'Self Development'),
(5,'The Subtle Art of Not Giving a F*ck', 'Self Development book by Mark Manson',15,'Self Development'),
(6,'The Everyday Hero Manifesto','Self Development book byRobin Sharma',15,'Self Development'),
(7,'The Everyday Hero Manifesto','Self Development book byRobin Sharma',15,'Self Development'),
(8,'The Everyday Hero Manifesto','Self Development book byRobin Sharma',15,'Self Development'),
(9,'The Everyday Hero Manifesto','Self Development book byRobin Sharma',15,'Self Development'),
(10,'The Everyday Hero Manifesto','Self Development book byRobin Sharma',15,'Self Development'),
(11,'The Everyday Hero Manifesto','Self Development book byRobin Sharma',15,'Self Development'),
(12,'Baby Animals Coloring Books for Kid','coloring book for kids',5,'Education'),
(13,'Baby Animals Coloring Books for Kid','coloring book for kids',5,'Education'),
(14,'Baby Animals Coloring Books for Kid','coloring book for kids',5,'Education'),
(15,'Baby Animals Coloring Books for Kid','coloring book for kids',5,'Education'),
(16,'The Intelligent Investor','The most famous investing book in the world by Benjamin Graham',50,'Education'),
(17,'The Intelligent Investor','The most famous investing book in the world by Benjamin Graham',50,'Education'),
(18,'The Intelligent Investor','The most famous investing book in the world by Benjamin Graham',50,'Education'),
(19,'The Intelligent Investor','The most famous investing book in the world by Benjamin Graham',50,'Education'),
(20,'The Intelligent Investor','The most famous investing book in the world by Benjamin Graham',50,'Education'),
(21,'South Africa','Travel book , for guide to travel to south africa',5,'Travel'),
(22,'South Africa','Travel book , for guide to travel to south africa',5,'Travel'),
(23,'South Africa','Travel book , for guide to travel to south africa',5,'Travel'),
(24,'West Africa','Travel book , for guide to travel to west africa',5,'Travel'),
(25,'West Africa','Travel book , for guide to travel to west africa',5,'Travel'),
(26,'West Africa','Travel book , for guide to travel to west africa',5,'Travel'),
(27,'Safari Ants Baggy Pants & Elephants','Travel book a Kenya odyssey with Susie Kelly',15,'Travel'),
(28,'Safari Ants Baggy Pants & Elephants','Travel book a Kenya odyssey with Susie Kelly',15,'Travel'),
(1,'Heroes Of Olympus','Fantasy book by Rick Riordan',10,'Fantasy'),
(2,'Heroes Of Olympus','Fantasy book by Rick Riordan',10,'Fantasy'),
(3,'Heroes Of Olympus','Fantasy book by Rick Riordan',10,'Fantasy'),
(4,'Heroes Of Olympus','Fantasy book by Rick Riordan',10,'Fantasy'),
(5,'Heroes Of Olympus','Fantasy book by Rick Riordan',10,'Fantasy'),
(6,'The Book Of Eli','Fantasy book has been adapted by the movie',20,'Fantasy'),
(7,'The Book Of Eli','Fantasy book has been adapted by the movie',20,'Fantasy'),
(8,'The Book Of Eli','Fantasy book has been adapted by the movie',20,'Fantasy'),
(9,'The Book Of Eli','Fantasy book has been adapted by the movie',20,'Fantasy'),
(10,'The Book Of Eli','Fantasy book has been adapted by the movie',20,'Fantasy'),
(11,'The Tales of Beedle The Bard', 'The famous author JK Rowling new book',50,'Fantasy'),
(12,'The Tales of Beedle The Bard', 'The famous author JK Rowling new book',50,'Fantasy'),
(13,'The Tales of Beedle The Bard', 'The famous author JK Rowling new book',50,'Fantasy'),
(14,'The Tales of Beedle The Bard', 'The famous author JK Rowling new book',50,'Fantasy'),
(15,'The Tales of Beedle The Bard', 'The famous author JK Rowling new book',50,'Fantasy'),
(16,'Ta Nehisi Coates The Water Dancer','Best selling author of Between The World And Me',20,'Fantasy'),
(17,'Ta Nehisi Coates The Water Dancer','Best selling author of Between The World And Me',20,'Fantasy'),
(18,'Ta Nehisi Coates The Water Dancer','Best selling author of Between The World And Me',20,'Fantasy'),
(19,'Ta Nehisi Coates The Water Dancer','Best selling author of Between The World And Me',20,'Fantasy'),
(20,'Ta Nehisi Coates The Water Dancer','Best selling author of Between The World And Me',20,'Fantasy'),
(21,'Circe','Author of the song of Achilles - Madeline Miller',10,'Fantasy'),
(22,'Circe','Author of the song of Achilles - Madeline Miller',12,'Fantasy'),
(23,'Circe','Author of the song of Achilles - Madeline Miller',10,'Fantasy'),
(24,'Circe','Author of the song of Achilles - Madeline Miller',14,'Fantasy'),
(25,'Circe','Author of the song of Achilles - Madeline Miller',9,'Fantasy'),
(26,'Circe','Author of the song of Achilles - Madeline Miller',11,'Fantasy'),
(27,'Circe','Author of the song of Achilles - Madeline Miller',11,'Fantasy'),
(28,'Circe','Author of the song of Achilles - Madeline Miller',16,'Fantasy'),
(1,'Ninth House Leigh Bardugo', 'The new york times best selling author',12,'Fantasy'),
(3,'Ninth House Leigh Bardugo', 'The new york times best selling author',22,'Fantasy'),
(5,'Ninth House Leigh Bardugo', 'The new york times best selling author',12,'Fantasy'),
(7,'Ninth House Leigh Bardugo', 'The new york times best selling author',12,'Fantasy'),
(9,'Ninth House Leigh Bardugo', 'The new york times best selling author',12,'Fantasy'),
(11,'Ninth House Leigh Bardugo', 'The new york times best selling author',13,'Fantasy'),
(13,'Ninth House Leigh Bardugo', 'The new york times best selling author',14,'Fantasy'),
(15,'Ninth House Leigh Bardugo', 'The new york times best selling author',15,'Fantasy'),
(17,'Ninth House Leigh Bardugo', 'The new york times best selling author',16,'Fantasy'),
(19,'Ninth House Leigh Bardugo', 'The new york times best selling author',17,'Fantasy'),
(21,'Ninth House Leigh Bardugo', 'The new york times best selling author',22,'Fantasy'),
(23,'Ninth House Leigh Bardugo', 'The new york times best selling author',23,'Fantasy'),
(25,'Ninth House Leigh Bardugo', 'The new york times best selling author',23,'Fantasy'),
(27,'Ninth House Leigh Bardugo', 'The new york times best selling author',12,'Fantasy');

